### ISSUE TITLE
Target not working with Vendingmachines as Store

### ISSUE THREAD

**Issue by TheRealSago** [ThatMadCap/madvendrob#1]
Hello, i tested your Script on our Testserver and i had the problem that the target dont show up, onlymy target from the VendingMachines to buy Items. I looked into your client.lua but cant fix it, i tried to change the distance of the target from my VendingMachines to 1.5 and yours on standard 2.5. Could you help, would be great thanks.

Video: https://clipchamp.com/watch/Pf9FONjuoNB

**Comment by ThatMadCap** [comment]
Do you have the item needed for the robbery in your inventory? It is set up for 'lockpick' by default.

**Comment by TheRealSago** [comment]
Yes, i have a few "lockpick" in my inventory. I use qs-inventory.

**Comment by ThatMadCap** [comment]
You're welcome to make the changes yourself and add an option for qs inventory and create a PR.

**Comment by TheRealSago** [comment]
I will look for it and let you know, im pretty sure its a simple fix, because quasar is very qb friendly and let the function most at the time original and a similar Script as yours is working to without big codes.
